In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

In [9]:
from sklearn.ensemble import IsolationForest

In [17]:
milk = pd.read_csv("C:\\Users\\DAI.STUDENTSDC\\Desktop\\Machine_Learning\\Datasets\\milk.csv", index_col = 0)
milk.head()

water  protein  fat  lactose   ash
Animal                                       
HORSE       90.1      2.6  1.0      6.9  0.35
ORANGUTAN   88.5      1.4  3.5      6.0  0.24
MONKEY      88.4      2.2  2.7      6.4  0.18
DONKEY      90.3      1.7  1.4      6.2  0.40
HIPPO       90.4      0.6  4.5      4.4  0.10

# isolation forest
- contamination :- The amount of contamination of the data set, i.e. the proportion of outliers in the data set. Used when fitting to define the threshold on the scores of the samples.

In [31]:
ifr = IsolationForest(random_state = 24, contamination = 0.05, n_estimators = 25)

In [37]:
ifr.fit_predict(milk)

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1, -1, -1])

In [39]:
milk.tail()

water  protein   fat  lactose   ash
Animal                                       
DEER       65.9     10.4  19.7      2.6  1.40
REINDEER   64.8     10.7  20.3      2.5  1.40
WHALE      64.8     11.1  21.2      1.6  1.70
SEAL       46.4      9.7  42.0      0.0  0.85
DOLPHIN    44.9     10.6  34.9      0.9  0.53

### on rfm dataset

In [55]:
rfm = pd.read_csv("C:\\Users\\DAI.STUDENTSDC\\Desktop\\Machine_Learning\\Cases\\Recency Frequency Monetary\\rfm_data_customer.csv", index_col = 0)
rfm.drop("most_recent_visit", axis = 1, inplace = True)

In [57]:
obj = IsolationForest(random_state= 24, contamination= 0.05, n_estimators= 100)
obj_pred=obj.fit_predict(rfm)

In [67]:
np.unique(obj_pred, return_counts= True)

(array([-1,  1]), array([ 2000, 37999], dtype=int64))

In [73]:
obj = IsolationForest(random_state= 24, n_estimators= 1000)
obj_pred=obj.fit_predict(rfm)

In [74]:
np.unique(obj_pred, return_counts= True)

(array([-1,  1]), array([ 8880, 31119], dtype=int64))